name: 'Check for external updates'
on:
  schedule:
    - cron: '20 4 * * *'
  workflow_dispatch:

jobs:
  build-matrix:
    name: Collect list of Flatpak manifests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      manifests: ${{ steps.get-manifests.outputs.manifests }}

    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false

    - id: get-manifests
      run: |
        MANIFESTS=$(find . -mindepth 2 -maxdepth 2 \( -iname "*.yaml" -o -iname "*.yml" -o -iname "*.json" \) | jq -R -s -c 'split("\n")[:-1]')
        echo "manifests=$MANIFESTS" >> $GITHUB_OUTPUT
        echo "::group::Manifests found"
        echo $MANIFESTS | jq
        echo "::endgroup::"

  flathub-data-checker-global:
    needs:
      - build-matrix
    name: ${{ matrix.manifest }}
    strategy:
      fail-fast: false
      matrix:
        manifest: ${{ fromJson(needs.build-matrix.outputs.manifests) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v5
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}

    - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
      env:
        GIT_AUTHOR_NAME: Flatpak External Data Checker
        GIT_COMMITTER_NAME: Flatpak External Data Checker
        GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      with:
        args: --update --never-fork ${{ matrix.manifest }}
