name: Prunerepo

on:
  workflow_dispatch:

jobs:
  prune:
    name: ostree prune
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:latest
      options: --privileged
    concurrency:
      group: repo-prune
      cancel-in-progress: false

    steps:
      - name: Prepare
        run: |
          dnf -y up && dnf -y install --setopt=install_weak_deps=False \
            flatpak \
            ostree \
            tar \
            zstd

      - name: Cache repo
        id: cache
        uses: actions/cache@v4
        with:
          path: repo
          key: repo-${{ github.sha }}
          restore-keys: repo-

      - name: Key
        env:
          GPGKEY: ${{ secrets.GPGKEY }}
        run: |
          echo "$GPGKEY" > ${{ github.repository_owner }}.private
          gpg --import ${{ github.repository_owner }}.private
          rm ${{ github.repository_owner }}.private

      - name: Update repo
        run: |
          mkdir -p repo/refs/remotes
          pushd repo
          for ref in $(ostree refs | grep '^runtime.*Debug'); do
              ostree refs --delete "$ref"
          done
          ostree fsck
          flatpak build-update-repo --generate-static-deltas --prune . --gpg-sign=dc812d3cb7855746

      - name: Upload repo
        uses: actions/upload-pages-artifact@v3
        with:
          path: repo/

  deploy:
    needs: prune
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
